version: "3.9"
services:
  nodejs-tokenization-treasury-api:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    environment:
     - ETH_HOST=$ETH_HOST
     - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
     - WEBHOOK=$WEBHOOK
     - PORT=$PORT
  tokenizer-db:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD 	
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    restart: always
  pg-admin:
    image: adminer
    links: 
    - tokenizer-db:db
    ports:
      - "8080:8080"

