version: "3.9"
services:
  nodejs-tokenization-treasury-api:
    image: registry.gitlab.com/i3-market/code/wp3/t3.3/nodejs-tokenization-treasury-api:develop
    ports:
      - "3001:3001"
    environment:
      - ETH_HOST=$ETH_HOST
      - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
      - WEBHOOK=$WEBHOOK
      - PORT=3001
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
    depends_on:
      - "tokenizer-db"
  tokenizer-db:
    image: postgres:14.2
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
    restart: always
