/*
 * Copyright (c) 2020-2022 in alphabetical order:
 * GFT, HOPU, Telesto Technologies
 *
 * This program and the accompanying materials are made
 * available under the terms of the EUROPEAN UNION PUBLIC LICENCE v. 1.2
 * which is available at https://gitlab.com/i3-market/code/wp3/t3.3/nodejs-tokenization-treasury-api/-/blob/master/LICENCE.md
 *
 *  License-Identifier: EUPL-1.2
 *
 *  Contributors:
 *    Vangelis Giannakosian (Telesto Technologies)
 *    Dimitris Kokolakis (Telesto Technologies)
 *    George Benos (Telesto Technologies)
 *    Germán Molina (HOPU)
 *
 */

const express = require('express');
const router = express.Router();
const paymentController = require('../controllers/paymentController');







/**
 * @swagger
 * /api/v1/operations:
 *   get:
 *     tags: [Operations]
 *     summary: Get list of operations.
 *     description: >
 *       Allow to know the performed operations and the status of them. Return the list of operations. The API endpoint
 *       admit filter by transfer transferId, status, date or user but not combine them.
 *     parameters:
 *       - name: transferId
 *         in: query
 *         required: false
 *         description: Filter by transfer id auto-generated by the system of an operation.
 *         schema:
 *           type: string
 *       - name: type
 *         in: query
 *         required: false
 *         description: Filter by operation type. Allowed values "exchange_in", "exchange_out", "clearing".
 *         schema:
 *           type: string
 *       - name: status
 *         in: query
 *         required: false
 *         description: Filter by operation status. Allowed values "open", "closed" and "in_progress".
 *         schema:
 *           type: string
 *       - name: user
 *         in: query
 *         required: false
 *         description: >
 *           Filter by operation user address in hexadecimal format i.e. 0xb794f5ea0ba39494ce839613fffba74279579268
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *        description: The list of the operations.
 *        content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/Operation'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.get('', paymentController.getOperations);


/**
 * @swagger
 * /api/v1/operations/exchange-in:
 *   post:
 *     tags: [Operations]
 *     summary: Retrieve the transaction object to perform a exchangeIn.
 *     description: >
 *       Retrieve the transaction object to perform a exchangeIn and create the operation.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           description: Address of the user that the marketplaces want to perform the exchangeIn.
 *           schema:
 *             type: object
 *             properties:
 *               userAddress:
 *                 type: string
 *                 example: '0xb5F3c73813B63336D8A3434B46f0164F57662f71'
 *               tokens:
 *                 type: Number
 *                 example: 60
 *     responses:
 *       200:
 *        description: Returns the transaction object and the operation description.
 *        content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 transferId:
 *                   type: string
 *                   format: uuid
 *                 transactionObject:
 *                   $ref: '#/components/schemas/TransactionObject'
 *                 operation:
 *                   $ref: '#/components/schemas/Operation'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.post('/exchange-in', paymentController.exchangeIn);

/**
 * @swagger
 * /api/v1/operations/exchange-out:
 *   post:
 *     tags: [Operations]
 *     summary: Retrieve the transaction object to perform a exchangeOut.
 *     description: >
 *       Retrieve the transaction object to perform a exchangeOut.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           description: Address of the user that the marketplaces want to perform the exchangeIn.
 *           schema:
 *             type: object
 *             properties:
 *               senderAddress:
 *                 type: string
 *                 example: '0xb5F3c73813B63336D8A3434B46f0164F57662f71'
 *               marketplaceAddress:
 *                 type: string
 *                 example: '0xaab3c73813B63336D8A3434B46f0164F57662e00'
 *     responses:
 *       200:
 *        description: Returns the transaction object and the operation description.
 *        content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 transferId:
 *                   type: string
 *                   format: uuid
 *                 transactionObject:
 *                   $ref: '#/components/schemas/TransactionObject'
 *                 operation:
 *                   $ref: '#/components/schemas/Operation'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.post('/exchange-out', paymentController.exchangeOut);


/**
 * @swagger
 * /api/v1/operations/clearing:
 *   post:
 *     tags: [Operations]
 *     summary: Retrieve the transaction object to start the Marketplace clearing operation.
 *     description: >
 *       Send all the tokens that the marketplaces owns from other marketplaces and send them to tre proper owner
 *       creating the proper clearing_in or clearing_out operation.
 *     responses:
 *       200:
 *        description: Returns the transaction object.
 *        content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 transferId:
 *                   type: string
 *                   format: uuid
 *                 transactionObject:
 *                   $ref: '#/components/schemas/TransactionObject'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.post('/clearing', paymentController.clearing);


/**
 * @swagger
 * /api/v1/operations/payment:
 *   post:
 *     tags: [Operations]
 *     summary: Generate the payment transaction object.
 *     description: >
 *       Pay fiat money to data providers or other marketplaces. It is required the transferId and the bank transfer
 *       code.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           description: transferId and transactionObject needed to put ad operation as paid out.
 *           schema:
 *             $ref: '#/components/schemas/Pay'
 *     responses:
 *       200:
 *        description: Returns the setPaid transaction object.
 *        content:
 *          application/json:
 *            schema:
 *              type: object
 *              properties:
 *                transferId:
 *                  type: string
 *                  format: uuid
 *                transactionObject:
 *                  $ref: '#/components/schemas/TransactionObject'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.post('/payment', paymentController.setPaid);


/**
 * @swagger
 * /api/v1/operations/feePayment:
 *   post:
 *     tags: [Operations]
 *     summary: Generate the fee payment transaction object.
 *     description: >
 *       Generates the transaction object needed to pay fee.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/FeePay'
 *     responses:
 *       200:
 *        description: Returns the feePayment transaction object and the operation description.
 *        content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 transferId:
 *                   type: string
 *                   format: uuid
 *                 transactionObject:
 *                   $ref: '#/components/schemas/TransactionObject'
 *                 operation:
 *                   $ref: '#/components/schemas/Operation'
 *       400:
 *        content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Error'
 *
 */
router.post('/feePayment', paymentController.feePayment);

module.exports = router;